### ISSUE TITLE
MDCT differences to tf.signal.mdct

### ISSUE THREAD

**Issue by faroit** [korneelvdbroek/audiocodec#1]
Hi, this is a great useful repo, thanks for it! Without having looked deeper into the implementation, was there a specific reason why mdct/imdct wasn't taken from [tf.signal](https://www.tensorflow.org/api_docs/python/tf/signal/mdct) ?

**Comment by korneelvdbroek** [comment]
Hi, [tf.signal.mdct](https://www.tensorflow.org/api_docs/python/tf/signal/mdct) was added in TF2.2 and my code dates from before that. 
So, no specific implementation reason!
